In [16]:
import numpy as np
from operator import *

In [53]:
x = np.array([
        [1,1,1],
        [4,5,6],
        [7,8,9]
    ])
# print(x.astype(float))
y = np.array([65, 75, 85])
theta = np.array([1, 3, 7])

def costfn(x, y, theta):
    xT = x.transpose()
    est = xT.dot(theta)
    m = len(xT)
    cost = (1.0 / (2 * m)) * reduce(lambda x,y: x + y*y, y - est, 0)
    return cost

def bestCostFn(x, y, thetas):
    costs = np.array([costfn(x,y,theta) for theta in thetas])
    print(costs)
    return costs.argmin(0)
    
# costfn(x, y, theta)
thetas = np.array([
        [1.1,4.2,6.9],
        [1,4,7],
        [1,3,7]
    ]) 
bestCostFn(x, y, thetas)
# costfn(x,y, np.array([2,1,4]))

[[ 1.  1.  1.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[ 3.04833333  2.33333333  4.5       ]


1

In [46]:
x = np.array([
        [1] * 12,
        [1,2,2,3,3,4,5,6,6,6,8,10]
    ])
y = np.array([-890,-1411,-1560,-2220,-2091,-2878,-3537,-3268,-3920,-4163,-5471,-5157])
thetas = np.array([
        [-1780.0, -530.9],
        [-569.6, 530.9],
        [-569.6, -530.9],
        [-1780.0, 530.9]
    ])
bestCostFn(x, y, thetas)

[   799910.275       16039401.46833333     67416.54166667
  10774282.50833333]


2

In [54]:
# np.array([[1,2,3],[4,5,6]]).astype(float)